version: 2.1
jobs:
  build:
    docker:
      - image: ocaml/opam2:4.08
        environment:
          TERM: xterm
    steps:
      - run:
          name: Update opam
          command: |
            opam remote remove --all default
            opam remote add default https://opam.ocaml.org
      - checkout
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n letters .
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl
            opam depext -y letters
      - run:
          name: Install OCaml dependencies
          command: |
            opam install --deps-only -y letters --with-test
      - run:
          name: Build
          command: opam config exec -- make
      - run:
          name: Test
          command: opam config exec -- make test-all

workflows:
  version: 2
  build:
    jobs:
      - build
